name: esde_android
description: This tools imports android apps into the ES-DE launcher
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.2

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  installed_apps: ^1.5.0
  file_picker: ^8.0.6
  dynamic_color: ^1.7.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  quiver: ^3.2.1
  flutter_launcher_icons: ^0.13.1
  permission_handler: ^11.3.1
  device_info_plus: ^11.3.0

flutter_launcher_icons:
  image_path: "icon/icon.png"
  android: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
